<?php 
require 'auth.php';
include 'config.php'; 

if($_SERVER['REQUEST_METHOD'] === 'POST'){
    ob_start();/*Starts output buffering.
                Output buffering is the temporary storage of data in memory before it is sent to its final 
                destination.
                From this point forward, any output generated by the script is stored in an internal buffer.
                at the end, at some point u'll see ob_get_clean. Read the comments there to fully understand*/

    $criteriaValue = $_POST['criteriaOption'] ?? '';
    $searchValue = $_POST['searchValue'] ?? '';
    $limit = $_POST['limit'] ?? 10;
    $page = $_POST['page'] ?? 1;
    $offset = ($page - 1) * $limit;
    $totalRows = 0;

    $searchTerm = "%$searchValue%";
    $result = null;

    /*Getting the chicken ID*/
    $chickenIdRes = $conn->query("SELECT id FROM animal_types WHERE name = 'Chicken'");
    $chickenIdRow = $chickenIdRes->fetch_assoc();
    $chickenId = (int)$chickenIdRow['id'];

    if($criteriaValue == 'name'){
        $undefinedName = ['un','und', 'unde', 'undef', 'def'];
        $isUndefined = false;
        foreach($undefinedName as $word){
            if(stripos($searchValue, $word) !== false){
                $isUndefined = true;
                break;
            }
        }
        if($isUndefined){
            $nullNameStmt = $conn->prepare("SELECT * FROM animals 
                                                WHERE tag_name IS NULL 
                                                    AND animal_type_id = ? AND gender = 'female'
                                                LIMIT ?, ?");
            $nullNameStmt->bind_param("iii",$chickenId , $offset, $limit);
            $nullNameStmt->execute();
            $result = $nullNameStmt->get_result();

            $countStmt = $conn->prepare("SELECT COUNT(*) as total FROM animals 
                                            WHERE tag_name IS NULL
                                                AND animal_type_id = ? AND gender = 'female'");
            $countStmt->bind_param("i", $chickenId);
            $countStmt->execute();
            $countRes = $countStmt->get_result();
            $totalRows = $countRes->fetch_assoc()['total'];
        }else{
            $nameStmt = $conn->prepare("SELECT * FROM animals 
                                            WHERE tag_name LIKE ? 
                                                AND animal_type_id = ? AND gender = 'female'
                                            LIMIT ?, ?");
            $nameStmt->bind_param("siii", $searchTerm, $chickenId, $offset, $limit);
            $nameStmt->execute();
            $result = $nameStmt->get_result();

            $countStmt = $conn->prepare("SELECT COUNT(*) as total FROM animals 
                                            WHERE tag_name LIKE ?
                                                AND animal_type_id = ? AND gender = 'female'");
            $countStmt->bind_param("si", $searchTerm, $chickenId);
            $countStmt->execute();
            $countRes = $countStmt->get_result();
            $totalRows = $countRes->fetch_assoc()['total'];
        }

    }elseif($criteriaValue == 'breed'){
        $unspecifiedBreed = ['no', 'spe', 'not spec'];
        /*Above, you can't write eg Not Specified cz we are going to check if part of the words are found. 
        If you write Not Specified, if someone types Not, it won't be a match cz Not specified is not found
        inside Not but Not is found inside Not Specied so you need to put here shorter versions of the word*/
        $isUnspecified = false;

        foreach($unspecifiedBreed as $word){
            if(stripos($searchValue, $word) !== false){/*stripos is case insensitive, strpos is case sensitive
            Why do we check if it is false instead of if it is true? Bcz stripos returns index positions when 
            true. Below, $needle is the word in the array and $haystack is the search value entered
                Case	                                                Return value
                $needle is found at the very start of $haystack	0       (position index)
                $needle is found later in $haystack	1, 2, 3…            (index of first match)
                $needle is not found                                    false
                
            Sth  u should know is that if it returns 0, in php 0 is false and 1 is true so in the if statement
            if you say if(...) == true, it will say no results found even though stripos is finding results so
            for stripos() one should check if the result is not false not if result is true*/
            
                $isUnspecified = true;
                break; /*This exits the foreach loop as soon as one of the words in the array is found in the
                         search value. This is to prevent the loop from continuing if a match is found */
            }
        }

        if($isUnspecified){
            $breedNullStmt = $conn->prepare("SELECT * FROM animals 
                                                WHERE breed_id IS NULL 
                                                    AND animal_type_id = ? AND gender = 'female'
                                                LIMIT ?, ?");
            $breedNullStmt->bind_param("iii", $chickenId, $offset, $limit);
            $breedNullStmt->execute();
            $result = $breedNullStmt->get_result();

            $countStmt = $conn->prepare("SELECT COUNT(*) as total FROM animals 
                                            WHERE breed_id IS NULL
                                                AND animal_type_id = ? AND gender = 'female'");
            $countStmt->bind_param("i", $chickenId);
            $countStmt->execute();
            $countRes = $countStmt->get_result();
            $totalRows = $countRes->fetch_assoc()['total'];
        }else{
            $breedNameStmt = $conn->prepare("SELECT id FROM breeds WHERE name LIKE ?");
            $breedNameStmt->bind_param("s", $searchTerm);
            $breedNameStmt->execute();
            $breedNameRes = $breedNameStmt->get_result();
            /*$breedNameRow = $breedNameRes->fetch_assoc(); fetch_assoc() only takes the first id in
               the result and not all of them so that's why the breed serach wasn't working well. If
               u serach 'k' and there are a number of breeds that start with K eg Kienyeji, Kenbro 
               etc. If you intended to see all the Kienyeji chicken but then SQL returned a list of
               ids with the names that have k but Kienyeji is not the first so eg: 1 = > Kenbro
                                                                                   2 = > Kienyeji
               fetch_assoc will pick the first id only so eg 1. And then in the if statement below
               when u look for a row with the id 1 and let's say it is not there in the table, it'll
               say 'no records found' and that will frustrate u cz u will be seeing Kienyeji somewhere
               in the list but when u see all of them, u won't be able to see them. That is why we need
               to loop the fetch_assoc() instead and add the ids in an array as u will see below*/

            $breedIDS = [];
            while($breedNameRow = $breedNameRes->fetch_assoc()){
                $breedIDS[] = $breedNameRow['id'];
            }

            if(empty($breedIDS)){
                $result = null;
            }else{

                $placeholders = implode(',',array_fill(0, count($breedIDS), '?'));
                /*In the code above:
                    array_fill() is used for creating arrays with a specified number of values
                    and with predifined values. The syntax is:
                        array_fill(starting index, no_of_array_elements, predifined_value)
                    So for the above, 0 is the index of the first value, count($breedIDS) 
                    tells us how many breedIds have been found and then '?' is the value
                    that will be allocated to every index so if the number of breedIds found
                    are 3, the final array will look like this: ['?', '?', '?']
                    Now as for the implode part, you know that in a prepared statement if you want
                    to have filler values u usually white the like this: "?,?,?" . We have to
                    convert the array that we've gotten into a string so implode() converts the
                    whole array into one string and separate the array values with a comma as we
                    have indicated. $placeholders will therefore look like this: "?,?,?"
                    Now as for the prepared statement, notive that we use IN() to check values
                    in an array*/
                
                $breedStmt = $conn->prepare("SELECT * FROM animals 
                                                WHERE breed_id IN ($placeholders)
                                                    AND animal_type_id = ? AND gender = 'female'
                                                LIMIT ?, ?");
                
                $dataTypes = str_repeat("i", count($breedIDS))."iii";
                /*We don't know how many ids there will be. One search could result in 1 while
                  another results in 3 so we count() the breedIDs found and add them to the other
                  3 definite integers cz we are sure about $chickenId, $offset and $limit*/

                $parameterArray = array_merge($breedIDS, [$chickenId, $offset, $limit]);
                /*This puts all the parameters into one array. See below how we will use it */
                $breedStmt->bind_param($dataTypes, ...$parameterArray);
                /*Since bind_param cannot directly access arrays, the three dots before
                  $parameterArray unpack the array enabling bind_param to use its values */

                $breedStmt->execute();
                $result = $breedStmt->get_result();


                $countStmt = $conn->prepare("SELECT COUNT(*) as total FROM animals 
                                                WHERE breed_id IN ($placeholders)
                                                    AND animal_type_id = ? AND gender = 'female'");

                $countTypes = str_repeat("i", count($breedIDS))."i";
                $countParamArray = array_merge($breedIDS, [$chickenId]);
                $countStmt->bind_param($countTypes, ...$countParamArray);
                $countStmt->execute();
                $countRes = $countStmt->get_result();
                $totalRows = $countRes->fetch_assoc()['total'];
            }
        }
        

    }elseif($criteriaValue == 'healthStatus'){

        $healthNameStmt = $conn->prepare("SELECT id FROM animal_statuses WHERE status_name LIKE ?");
        $healthNameStmt->bind_param("s", $searchTerm);
        $healthNameStmt->execute();
        $healthNameRes = $healthNameStmt->get_result();
        $healthNameRow = $healthNameRes->fetch_assoc();
        if($healthNameRow == null){
            $result = null;
        }else{
            $healthId = $healthNameRow['id'];
            $healthStmt = $conn->prepare("SELECT * FROM animals WHERE health_status_id = ? 
                                            AND animal_type_id = ? AND gender = 'female'
                                            LIMIT ?, ?");
            $healthStmt->bind_param("iiii", $healthId, $chickenId, $offset, $limit);
            $healthStmt->execute();
            $result = $healthStmt->get_result();

            $countStmt = $conn->prepare("SELECT COUNT(*) as total FROM animals WHERE health_status_id = ?
                                            AND animal_type_id = ? AND gender = 'female'");
            $countStmt->bind_param("ii", $healthId, $chickenId);
            $countStmt->execute();
            $countRes = $countStmt->get_result();
            $totalRows = $countRes->fetch_assoc()['total'];
        }

    }
    elseif($criteriaValue == 'lifeStatus'){
        $lifeNameStmt = $conn->prepare("SELECT id FROM animal_lifecycle_statuses WHERE name LIKE ?");
        $lifeNameStmt->bind_param("s", $searchTerm);
        $lifeNameStmt->execute();
        $lifeNameRes = $lifeNameStmt->get_result();
        $lifeNameRow = $lifeNameRes->fetch_assoc();
        if($lifeNameRow == null){
            $result = null;
        }else{
            $lifeId = $lifeNameRow['id'];
            $lifeStmt = $conn->prepare("SELECT * FROM animals WHERE lifecycle_status_id = ? 
                                            AND animal_type_id = ? AND gender = 'female'
                                        LIMIT ?, ?");
            $lifeStmt->bind_param("iiii", $lifeId, $chickenId, $offset, $limit);
            $lifeStmt->execute();
            $result = $lifeStmt->get_result();

            $countStmt = $conn->prepare("SELECT COUNT(*) as total FROM animals WHERE lifecycle_status_id = ?
                                            AND animal_type_id = ? AND gender = 'female'");
            $countStmt->bind_param("ii", $lifeId, $chickenId);
            $countStmt->execute();
            $countRes = $countStmt->get_result();
            $totalRows = $countRes->fetch_assoc()['total'];
        }

    }
    elseif($criteriaValue == 'dateCreated'){
        $dateStmt = $conn->prepare("SELECT * FROM animals
                        WHERE created_at LIKE ? 
                        AND animal_type_id = ? AND gender = 'female'
                        LIMIT ?,?");
        $dateStmt->bind_param("siii", $searchTerm, $chickenId, $offset, $limit);
        $dateStmt->execute();
        $result = $dateStmt->get_result();
    }
    elseif(empty($criteriaValue) || empty($searchValue)){
        $emptyStmt = $conn->prepare("SELECT * FROM animals 
                                        WHERE animal_type_id = ? AND gender = 'female'
                                        LIMIT ?, ?");
        $emptyStmt->bind_param("iii", $chickenId, $offset, $limit);
        $emptyStmt->execute();
        $result = $emptyStmt->get_result();

        $countStmt = $conn->prepare("SELECT COUNT(*) as total FROM animals
                                        WHERE animal_type_id = ? AND gender = 'female'");
        $countStmt->bind_param("i", $chickenId);
        $countStmt->execute();
        $countRes = $countStmt->get_result();
        $totalRows = $countRes->fetch_assoc()['total'];
        
    }

    /*Getting the health status id */
    $healthy = $conn->query("SELECT id FROM animal_statuses WHERE status_name = 'Healthy'");
    $healthyRes = $healthy->fetch_assoc();
    $sick = $conn->query("SELECT id FROM animal_statuses WHERE status_name = 'Sick'");
    $sickRes = $sick->fetch_assoc();
    $quara = $conn->query("SELECT id FROM animal_statuses WHERE status_name = 'Quarantined'");
    $quaraRes = $quara->fetch_assoc();

    $healthStatusName = "undefined";
    $healthStatusColor = "undetermined";

    /*Getting the life status id*/
    $alive = $conn->query("SELECT id FROM animal_lifecycle_statuses WHERE name = 'Alive in the farm'");
    $aliveRes = $alive->fetch_assoc();
    $sold = $conn->query("SELECT id FROM animal_lifecycle_statuses WHERE name = 'Sold'");
    $soldRes = $sold->fetch_assoc();
    $dead = $conn->query("SELECT id FROM animal_lifecycle_statuses WHERE name = 'Dead'");
    $deadRes = $dead->fetch_assoc();

    $lifeStatusName = "undefined";
    $lifeStatusColor = "undetermined";

    if($result && $result->num_rows > 0){/*The first part ensures $result exists before accessing it. I've done this cz I've 
    initialized $result as null so I need to check if it actually contains sth or I'll get an error for checking if sth null has a 
    number of rows*/
        while($row = $result->fetch_assoc()){
            /*Storing the id of the respective field for future use*/
            $rowId = $row['id'];

            $breedName = '';
            $breedId = (int)$row['breed_id'];
            if($row['breed_id'] != null){
                $breedStmt = $conn->prepare("SELECT name FROM breeds WHERE id = ?");
                $breedStmt->bind_param("i", $breedId);
                $breedStmt->execute();
                $breedRes = $breedStmt->get_result();
                $breedRow = $breedRes->fetch_assoc();
                $breedName = $breedRow['name'];
            }else{
                $breedName = 'Not specified';
            }

            /*Determining color depending of health status id */
            if((int)$row['health_status_id'] == (int)$healthyRes['id']){
                $healthStatusName = "Healthy";
                $healthStatusColor = "green";
            }elseif((int)$row['health_status_id'] == (int)$sickRes['id']){
                $healthStatusName = "Sick";
                $healthStatusColor = "red";
            }elseif((int)$row['health_status_id'] == (int)$quaraRes['id']){
                $healthStatusName = "Quarantined";
                $healthStatusColor = "yellow";
            }

            /*Determining color depending of lifecycle status id */
            if((int)$row['lifecycle_status_id'] == (int)$aliveRes['id']){
                $lifeStatusName = "Alive in the farm";
                $lifeStatusColor = "green";
            }elseif((int)$row['lifecycle_status_id'] == (int)$soldRes['id']){
                $lifeStatusName = "Sold";
                $lifeStatusColor = "yellow";
            }elseif((int)$row['lifecycle_status_id'] == (int)$deadRes['id']){
                $lifeStatusName = "Dead";
                $lifeStatusColor = "red";
            }
            ?>
            <tr>
                <td><input type="checkbox" name="rowSelected" value="<?= $rowId ?>"></td>
                <td><?= htmlspecialchars($row['tag_name'] ?? 'Undefined') ?></td>
                <td><?= htmlspecialchars($breedName) ?></td>
                <td><?= htmlspecialchars($healthStatusName) ?></td>
                <td><?= htmlspecialchars($lifeStatusName) ?></td>
                <?php $newDate = new DateTime($row['created_at'])?>
                <td><?= htmlspecialchars($newDate->format('d-m-Y')) ?></td>
                <td><button type="button" class="triggerEdit" value="<?= $rowId ?>">Edit</button></td>
                <td><button type="button" class="triggerDelete" value="<?= $rowId ?>">Delete</button></td>
            </tr>
            <?php
        }
    }else{
        ?>
        <tr>
            <td colspan="8">No records found</td>
        </tr>
        <?php
    }

    $rowsHtml = ob_get_clean();/*I've ended the output buffering here and stored it in rowsHtml. $rowsHtml
                                therefore contains all the content that is to be displayed in the table. 
                                Below I will calculate the totalPages and then encode the data to json and
                                that is how dairy.js will access it.*/

    $totalPages = max(1, ceil($totalRows / $limit));/*I've set the default totalRows as zero so if there are
    no records, the ceil will return 0. This is bad for the UI cz it'll say zero pages. For safety, I'm forcing
    a minimum of 1 (yes, max sets the minimum) so that if nothing is found then it still displays Page 1 of 1*/

    echo json_encode([
        "rows" => $rowsHtml,
        "totalPages" => $totalPages
    ]);
  
}
?>